<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Activity Logs Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        h1, h2, h3 { margin: 0; }
        .header { text-align: center; margin-bottom: 16px; }
        .meta { font-size: 11px; margin-bottom: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #ccc; padding: 4px 6px; text-align: left; }
        th { background: #f3f3f3; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .small { font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>RovicApp - Activity Logs Report</h1>
        <p class="small">Admin &amp; Super Admin Audit Trail</p>
    </div>

    <div class="meta">
        <div><strong>Period:</strong> {{ $periodLabel }} ({{ $startDate->format('Y-m-d') }} to {{ $endDate->format('Y-m-d') }})</div>
        <div><strong>Printed by:</strong> {{ $printedBy }}</div>
        <div><strong>Generated at:</strong> {{ $generatedAt->format('Y-m-d H:i:s') }}</div>
        <div><strong>Total Logs:</strong> {{ $totalLogs }}</div>
    </div>

    @php
        $roleLabels = [
            'super_admin' => 'Super Admin',
            'admin' => 'Admin',
            'customer' => 'Customer',
        ];

        $actionLabels = [
            // Orders
            'order_status_updated' => 'Order status updated',
            'order_payment_approved' => 'Payment approved',
            'order_payment_rejected' => 'Payment rejected',

            // Products
            'product_created' => 'Product created',
            'product_updated' => 'Product updated',
            'product_deleted' => 'Product deleted',
            'product_best_selling_toggled' => 'Product best-selling status changed',
            'product_active_toggled' => 'Product visibility changed',
            'product_stock_adjusted' => 'Product stock adjusted',
            'product_bulk_stock_updated' => 'Product stock updated (bulk)',

            // Categories
            'category_created' => 'Category created',
            'category_updated' => 'Category updated',
            'category_deleted' => 'Category deleted',
            'category_active_toggled' => 'Category visibility changed',

            // Payment settings
            'payment_setting_created' => 'Payment method added',
            'payment_setting_updated' => 'Payment method updated',
            'payment_setting_deleted' => 'Payment method deleted',
            'payment_setting_active_toggled' => 'Payment method visibility changed',

            // Users
            'user_created' => 'User created',
            'user_updated' => 'User updated',
            'user_deleted' => 'User deleted',
            'user_verification_toggled' => 'User verification updated',
        ];
    @endphp

    <table>
        <thead>
            <tr>
                <th class="small">#</th>
                <th class="small">Date / Time</th>
                <th class="small">User</th>
                <th class="small">Role</th>
                <th class="small">Action</th>
                <th class="small">Description</th>
                <th class="small">IP Address</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($logs as $index => $log)
                @php
                    $user = $log->user;
                    $userName = $user ? $user->name : 'System / Guest';
                    $roleKey = $user->role ?? null;
                    $roleLabel = $roleKey ? ($roleLabels[$roleKey] ?? ucwords(str_replace('_', ' ', $roleKey))) : 'System';
                    $actionKey = $log->action;
                    $actionLabel = $actionLabels[$actionKey] ?? ucwords(str_replace('_', ' ', $actionKey));
                @endphp
                <tr>
                    <td class="text-center small">{{ $index + 1 }}</td>
                    <td class="small">{{ $log->created_at?->format('Y-m-d H:i') }}</td>
                    <td class="small">{{ $userName }}</td>
                    <td class="small">{{ $roleLabel }}</td>
                    <td class="small">{{ $actionLabel }}</td>
                    <td class="small">{{ $log->description ?: '-' }}</td>
                    <td class="small">{{ $log->ip_address ?: '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" class="text-center small">No activity logs found for this period.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <p class="small" style="margin-top: 16px;">
        This PDF is generated by the system based on the current database records and is intended as a tamper-resistant snapshot of admin and super admin activities for the selected period.
    </p>
</body>
</html>
